name: CI Pipeline

on:
  push:
    branches: ["**"]
    tags: ["!*"]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-lint:
    name: Commit Lint
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Commit Lint
      - name: Set up Commit Lint
        uses: wagoid/commitlint-github-action@v4

  build:
    name: Build and Test
    needs: commit-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      # Run linters
      - name: Lint with ruff
        run: |
          if command -v ruff &>/dev/null; then
            ruff .
          fi

      # Run tests
      - name: Run tests
        run: |
          if [ -d tests ]; then
            python -m pytest -q || [[ $? -eq 5 ]] || exit 1
          else
            echo "No tests directory found, skipping tests."
          fi
